[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "todo"
version = "0.0.0"
dependencies = [
    "python-fasthtml"
]

[project.optional-dependencies]
dev = [
]

[tool.ruff]
line-length = 120